spring.datasource.url=jdbc:mysql://localhost:3306/blood_donation
spring.datasource.username=root
spring.datasource.password=Zigzac1234#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Tắt tự động tạo bảng của JPA/Hibernate vì bạn dùng file SQL riêng
spring.jpa.hibernate.ddl-auto=none 

# Thuộc tính mới thay thế 'initialization-mode' để chạy data.sql/schema.sql
spring.sql.init.mode=always

# Hiển thị các câu lệnh SQL trong console
spring.jpa.show-sql=true